### ISSUE TITLE
Existing Snapshots with Different Name Cause verify_no_existing_snapshot.yml to Fail

### ISSUE THREAD

**Issue by nick-a-meyer** [swapdisk/lvm_snapshots#12]
# Existing Snapshots with Different Name Cause [verify_no_existing_snapshot.yml](../blob/main/roles/lvm_snapshots/tasks/verify_no_existing_snapshot.yml) to Fail

Check fails if another snapshot exists on the same LV even if the names are different.

## [Documentation Specifies](../tree/main/roles/lvm_snapshots#lvm_snapshots_action)
Both the `check` and `create` actions will verify free space and should fail if there is not enough. A check or create action should fail if any snapshots already exist for the given `snapshot_set_name`.

**Comment by nick-a-meyer** [comment]
I can create a PR for this.

**Comment by ygalblum** [comment]
@swapdisk wrote the doc before I implemented it. I guess I misread it, but it did make sense to me . So, I'd like to get @swapdisk's opinion before we decide if it's the code or document that we should fix.

**Comment by swapdisk** [comment]
My intention was that the documented fail should happen if there would be a collision with existing snapshot volume names. I did not expect it to prevent using an origin volume that has a snapshot with different name. PR #13 looks good.
