### ISSUE TITLE
Package installation for required utilities is absent.

### ISSUE THREAD

**Issue by heatmiser** [swapdisk/lvm_snapshots#16]
The revert task utilizes `ansible.builtin.unarchive` module for restoring the boot backup. As stated in [the unarchive module documentation](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/unarchive_module.html):
```
- Requires zipinfo and gtar/unzip command on target host.
- Requires zstd command on target host to expand .tar.zst files.
- Can handle .zip files using unzip as well as .tar, .tar.gz, .tar.bz2, .tar.xz, and .tar.zst files using gtar.
```
Should the addition of an initial task which installs the `tar` and  `unzip` packages be added? Or leave the installation of gtar/unzip as a stated prerequisite of utilizing this lvm_snapshot role?

**Comment by swapdisk** [comment]
> The `tar` package will always be present on RHEL hosts... 

Well, I'm wrong about this. Apparently, there are no such dependencies on RHEL8 as I discovered just now playing with LVM snapshots on a workshop EC2 instance.

I'll add a task to make sure `tar` is present.
